version: 2
updates:
  - package-ecosystem: pip
    directory: "/.config"
    schedule:
      day: sunday
      interval: weekly
    labels:
      - dependencies
      - skip-changelog
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "monthly"
    # disabled as it adds noise, as all deps are used only during build
    open-pull-requests-limit: 0
    labels:
      - dependencies
      - skip-changelog
    versioning-strategy: increase
    allow:
      - dependency-type: "all"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: daily
    open-pull-requests-limit: 3
    labels:
      - "skip-changelog"
