version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 2
    labels:
      - "skip-changelog"
      - "dependencies"
    versioning-strategy: increase
    allow:
      - dependency-type: "all"
