---
repos:
  - repo: local
    hooks:
      - name: update-schemas
        id: update-schemas
        language: python
        pass_filenames: false
        always_run: true
        entry: python src/update-schemas.py
  - repo: https://github.com/pre-commit/pre-commit-hooks.git
    rev: v4.2.0
    hooks:
      - id: end-of-file-fixer
        exclude: >
          (?x)^(
            data/.*
          )$
      - id: trailing-whitespace
      - id: mixed-line-ending
      - id: check-byte-order-marker
      - id: check-executables-have-shebangs
      - id: check-merge-conflict
  - repo: https://github.com/streetsidesoftware/cspell-cli
    rev: v5.9.1
    hooks:
      - id: cspell
        # entry: codespell --relative
        args: [--relative, --no-progress, --no-summary]
        name: Spell check with cspell
  - repo: https://github.com/pre-commit/mirrors-prettier
    # keep it before markdownlint and eslint
    rev: "v2.6.2"
    hooks:
      - id: prettier
        exclude: >
          (?x)^(
            data/.*
          )$
        always_run: true
        additional_dependencies:
          - prettier
          - prettier-plugin-sort-json
  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.31.1
    hooks:
      - id: markdownlint
  - repo: https://github.com/codespell-project/codespell
    rev: v2.1.0
    hooks:
      - id: codespell
        entry: codespell --ignore-words=.config/dictionary.txt
        exclude: >
          (?x)^(
            data/.*|
            package-lock.json
          )$
  - repo: https://github.com/adrienverge/yamllint.git
    rev: v1.26.3
    hooks:
      - id: yamllint
        files: \.(yaml|yml)$
        types: [file, yaml]
        entry: yamllint --strict
