proseWrap: always
jsonRecursiveSort: true # prettier-plugin-sort-json
overrides:
  - files:
      - "*.md"
    options:
      # compatibility with markdownlint
      proseWrap: always
      printWidth: 80
