---
repos:
  - repo: local
    hooks:
      - name: rebuild schemas
        id: rebuild
        language: python
        pass_filenames: false
        always_run: true
        entry: python src/rebuild.py
  - repo: https://github.com/pre-commit/pre-commit-hooks.git
    rev: v4.3.0
    hooks:
      - id: end-of-file-fixer
        exclude: >
          (?x)^(
            data/.*
          )$
      - id: trailing-whitespace
      - id: mixed-line-ending
      - id: check-byte-order-marker
      - id: check-executables-have-shebangs
      - id: check-merge-conflict
  - repo: https://github.com/streetsidesoftware/cspell-cli
    rev: latest
    hooks:
      - id: cspell
        # entry: codespell --relative
        args: [--relative, --no-progress, --no-summary]
        name: Spell check with cspell
        exclude: >
          (?x)^(
            (negative_test|test)/.*\.md
          )$
  - repo: https://github.com/pre-commit/mirrors-prettier
    # keep it before markdownlint and eslint
    rev: "v2.7.1"
    hooks:
      - id: prettier
        exclude: >
          (?x)^(
            (negative_test|test)/.*\.md|
            f/ansible-(tasks|playbook).json|
            data/.*
          )$
        always_run: true
        additional_dependencies:
          - prettier
          - prettier-plugin-sort-json
  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.31.1
    hooks:
      - id: markdownlint
        exclude: >
          (?x)^(
            (negative_test|test)/.*\.md
          )$
  - repo: https://github.com/codespell-project/codespell
    rev: v2.1.0
    hooks:
      - id: codespell
        entry: codespell --ignore-words=.config/dictionary.txt
        exclude: >
          (?x)^(
            data/.*|
            package-lock.json
          )$
  - repo: https://github.com/adrienverge/yamllint.git
    rev: v1.27.1
    hooks:
      - id: yamllint
        files: \.(yaml|yml)$
        types: [file, yaml]
        entry: yamllint --strict
  - repo: https://github.com/psf/black
    rev: 22.6.0
    hooks:
      - id: black
        language_version: python3
  - repo: https://github.com/pycqa/flake8.git
    rev: 4.0.1
    hooks:
      - id: flake8
        language_version: python3
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.961
    hooks:
      - id: mypy
        # empty args needed in order to match mypy cli behavior
        args: [--strict]
        # additional_dependencies:
  - repo: https://github.com/pycqa/pylint
    rev: v2.14.4
    hooks:
      - id: pylint
        # additional_dependencies:
