---
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks.git
  rev: v4.1.0
  hooks:
  - id: end-of-file-fixer
    exclude: >
      (?x)^(
        data/.*
      )$
  - id: trailing-whitespace
  - id: mixed-line-ending
  - id: check-byte-order-marker
  - id: check-executables-have-shebangs
  - id: check-merge-conflict
- repo: https://github.com/codespell-project/codespell
  rev: v2.1.0
  hooks:
  - id: codespell
    entry: codespell --ignore-words=words.txt
    exclude: >
      (?x)^(
        data/.*|
        package-lock.json
      )$
- repo: https://github.com/adrienverge/yamllint.git
  rev: v1.26.3
  hooks:
  - id: yamllint
    files: \.(yaml|yml)$
    types: [file, yaml]
    entry: yamllint --strict
