---
dictionaryDefinitions:
  - name: words
    path: .config/dictionary.txt
    addWords: true
dictionaries:
  # Use `cspell-cli trace word` to check where a work is defined
  - en_US
  - bash
  - words
  - python
  - seealso
ignorePaths:
  - cspell.config.yaml
  - .gitignore
  # Generated content
  - data/*.*
  - requirements.txt
