# see https://taskfile.dev/#/
version: "3"
output: group
vars:
  HOSTNAME:
    sh: echo ${HOSTNAME:-localhost}
  VERSION:
    sh: node -p "require('./package.json').version"
env: &env
  FORCE_COLOR: "true"
  PRE_COMMIT_COLOR: always
  # basically the same thing from .envrc file:
  VIRTUAL_ENV: # "{{.VIRTUAL_ENV}}"
    sh: echo "${VIRTUAL_ENV:-out/venvs/${HOSTNAME:-localhost}}"
tasks:
  default:
    desc: Run most commands
    deps:
      - lint
      - test
    cmds:
      - echo Passed all checks!
  setup:
    desc: Install dependencies
    run: once # avoid duplicate runs as all task depend on this
    cmds:
      - ./tools/test-setup.sh
      - npm ci
    sources:
      - package-lock.json
      - package.json
      - tools/test-setup.sh
  deps:
    desc: Update dependencies
    deps:
      - setup
    cmds:
      - source $VIRTUAL_ENV/bin/activate && pip-compile -q --no-header
        --no-annotate --output-file=.config/requirements.txt
        .config/requirements.in
      - npm run deps
  lint:
    desc: Lint the project
    deps:
      - setup
    env:
      PRE_COMMIT_COLOR: always
    cmds:
      - $VIRTUAL_ENV/bin/python3 -m pre_commit run -a
    silent: true
    sources:
      - "*"
      - "*.*"
      - ".config"
      - ".github"
      - ".vscode"
      - data
      - f
      - negative_test
      - src/**
      - test/**
  test:
    desc: Run all tests
    deps:
      - setup
      - lint
    cmds:
      - npm run test
      # Fail if git reports dirty after test run:
      - sh -c '[ -z "`git status --porcelain negative_test/ test/`" ]'
    sources:
      - f/
      - negative_test/
      - test/
      - src/
      - package.json
      - package-lock.json
      - Taskfile.yml
      - tsconfig.json
    interactive: true
  pr:
    desc: Opens a pull request using gh
    deps:
      - lint
    cmds:
      - gh pr create
    interactive: true
