- hosts: localhost
  vars_prompt:

    - name: username
      prompt: What is your username?
      private: false
      tags:
        - foo
        - bar

    - name: password
      prompt: What is your password?
      tags: foo

- name: foo
  import_playbook: included.yml
