- hosts: localhost
  vars_prompt:

    - name: username
      prompt: What is your username?
      private: false

    - name: password
      prompt: What is your password?

- name: foo
  import_playbook: included.yml
