---
# v1 role meta (standalone)
galaxy_info:
  author: foo.bar # <-- that is a valid author name because is not a valid github username
  description: foo
  min_ansible_version: "2.9"
  company: foo
  license: MIT
  platforms:
    - name: Alpine
      versions:
        - all
