name: dump

on:
  push:  # only publishes pushes to the main branch to TestPyPI
    branches:  # any integration branch but not tag
    - "master"
    paths:
    - 'data'
    - 'requirements.txt'
  pull_request:
    paths:
    - 'data'
    - 'requirements.txt'

jobs:
  dump:
    name: >-
      ${{ matrix.env.TOXENV }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        python-version:
        - 3.8
        os:
        - ubuntu-20.04
        env:
        - TOXENV: dump
    env:
      TOX_PARALLEL_NO_SPINNER: 1
      FORCE_COLOR: 1

    steps:
    - name: Check out src from Git
      uses: actions/checkout@v2
      with:
        fetch-depth: 0  # needed by setuptools-scm

    # https://github.com/actions/cache
    - uses: actions/cache@v2
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/setup.cfg') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install test deps
      run: |
        npm ci
        python3 -m pip install --upgrade tox

    - name: Log installed dists
      run: >-
        python3 -m pip freeze --all

    - name: >-
        Initialize tox envs
      run: >-
        python3 -m tox --notest --skip-missing-interpreters false -vv
      env: ${{ matrix.env }}

    - name: Test with tox
      run: |
        python3 -m tox
      env: ${{ matrix.env }}
